workflows:
  movie:
    name: Unit Testing
    scripts:
      - echo "Testing"
      - name: Flutter test
        working_directory: modules/movie
        script: flutter test
    triggering:
      events:
        - push