// Mocks generated by Mockito 5.4.0 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i19;
import 'dart:typed_data' as _i20;

import 'package:core/common/failure.dart' as _i8;
import 'package:core/data/datasources/db/database_helper.dart' as _i16;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/data/model/movie_table.dart' as _i18;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i17;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i14;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i12;
import 'package:tv/data/model/season_detail_model.dart' as _i4;
import 'package:tv/data/model/tv_series_detail_model.dart' as _i3;
import 'package:tv/data/model/tv_series_model.dart' as _i13;
import 'package:tv/data/model/tv_series_table.dart' as _i15;
import 'package:tv/domain/entities/season_detail.dart' as _i11;
import 'package:tv/domain/entities/tv_series.dart' as _i9;
import 'package:tv/domain/entities/tv_series_detail.dart' as _i10;
import 'package:tv/domain/repositories/tv_series_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonDetailResponse_2 extends _i1.SmartFake
    implements _i4.SeasonDetailResponse {
  _FakeSeasonDetailResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i6.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
      getOnTheAirTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getOnTheAirTvSeries,
              [],
            ),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                    _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
              this,
              Invocation.method(
                #getOnTheAirTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                    _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                    _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
      getRecommendationTvSeries({required int? id}) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendationTvSeries,
              [],
              {#id: id},
            ),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                    _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
              this,
              Invocation.method(
                #getRecommendationTvSeries,
                [],
                {#id: id},
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> searchTvSeries(
          {required String? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [],
          {#query: query},
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [],
            {#query: query},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>> getTvSeriesDetail(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [],
          {#id: id},
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>.value(
                _FakeEither_0<_i8.Failure, _i10.TvSeriesDetail>(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [],
            {#id: id},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>> getSeasonDetail({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [],
          {
            #id: id,
            #seasonNumber: seasonNumber,
          },
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>.value(
                _FakeEither_0<_i8.Failure, _i11.SeasonDetail>(
          this,
          Invocation.method(
            #getSeasonDetail,
            [],
            {
              #id: id,
              #seasonNumber: seasonNumber,
            },
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveTvSeriesWatchlist(
          {required _i10.TvSeriesDetail? tvSeriesDetail}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTvSeriesWatchlist,
          [],
          {#tvSeriesDetail: tvSeriesDetail},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #saveTvSeriesWatchlist,
            [],
            {#tvSeriesDetail: tvSeriesDetail},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeTvSeriesWatchlist(
          {required _i10.TvSeriesDetail? tvSeriesDetail}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvSeriesWatchlist,
          [],
          {#tvSeriesDetail: tvSeriesDetail},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #removeTvSeriesWatchlist,
            [],
            {#tvSeriesDetail: tvSeriesDetail},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToWatchlist({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
      getTvSeriesWatchlist() => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesWatchlist,
              [],
            ),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                    _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
              this,
              Invocation.method(
                #getTvSeriesWatchlist,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i12.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i13.TvSeriesModel>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvSeries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i13.TvSeriesModel>>.value(<_i13.TvSeriesModel>[]),
      ) as _i7.Future<List<_i13.TvSeriesModel>>);
  @override
  _i7.Future<List<_i13.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i13.TvSeriesModel>>.value(<_i13.TvSeriesModel>[]),
      ) as _i7.Future<List<_i13.TvSeriesModel>>);
  @override
  _i7.Future<List<_i13.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i13.TvSeriesModel>>.value(<_i13.TvSeriesModel>[]),
      ) as _i7.Future<List<_i13.TvSeriesModel>>);
  @override
  _i7.Future<_i3.TvSeriesDetailResponse> getTvSeriesDetail(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<_i3.TvSeriesDetailResponse>.value(
            _FakeTvSeriesDetailResponse_1(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [],
            {#id: id},
          ),
        )),
      ) as _i7.Future<_i3.TvSeriesDetailResponse>);
  @override
  _i7.Future<List<_i13.TvSeriesModel>> getRecommendationTvSeries(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationTvSeries,
          [],
          {#id: id},
        ),
        returnValue:
            _i7.Future<List<_i13.TvSeriesModel>>.value(<_i13.TvSeriesModel>[]),
      ) as _i7.Future<List<_i13.TvSeriesModel>>);
  @override
  _i7.Future<List<_i13.TvSeriesModel>> searchTvSeries(
          {required String? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [],
          {#query: query},
        ),
        returnValue:
            _i7.Future<List<_i13.TvSeriesModel>>.value(<_i13.TvSeriesModel>[]),
      ) as _i7.Future<List<_i13.TvSeriesModel>>);
  @override
  _i7.Future<_i4.SeasonDetailResponse> getSeasonDetail({
    required int? id,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [],
          {
            #id: id,
            #seasonNumber: seasonNumber,
          },
        ),
        returnValue: _i7.Future<_i4.SeasonDetailResponse>.value(
            _FakeSeasonDetailResponse_2(
          this,
          Invocation.method(
            #getSeasonDetail,
            [],
            {
              #id: id,
              #seasonNumber: seasonNumber,
            },
          ),
        )),
      ) as _i7.Future<_i4.SeasonDetailResponse>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i14.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertTvSeriesWatchlist(
          {required _i15.TvSeriesTable? tvSeriesTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTvSeriesWatchlist,
          [],
          {#tvSeriesTable: tvSeriesTable},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> removeTvSeriesWatchlist(
          {required _i15.TvSeriesTable? tvSeriesTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvSeriesWatchlist,
          [],
          {#tvSeriesTable: tvSeriesTable},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i15.TvSeriesTable?> getTvSeriesById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<_i15.TvSeriesTable?>.value(),
      ) as _i7.Future<_i15.TvSeriesTable?>);
  @override
  _i7.Future<List<_i15.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i7.Future<List<_i15.TvSeriesTable>>.value(<_i15.TvSeriesTable>[]),
      ) as _i7.Future<List<_i15.TvSeriesTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i16.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i17.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i7.Future<_i17.Database?>.value(),
      ) as _i7.Future<_i17.Database?>);
  @override
  _i7.Future<int> insertMovieWatchlist(
          {required _i18.MovieTable? movieTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMovieWatchlist,
          [],
          {#movieTable: movieTable},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
  @override
  _i7.Future<int> removeMovieWatchlist(
          {required _i18.MovieTable? movieTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMovieWatchlist,
          [],
          {#movieTable: movieTable},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<int> insertTvSeriesWatchlist(
          {required _i15.TvSeriesTable? tvSeriesTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTvSeriesWatchlist,
          [],
          {#tvSeriesTable: tvSeriesTable},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
  @override
  _i7.Future<int> removeTvSeriesWatchlist(
          {required _i15.TvSeriesTable? tvSeriesTable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvSeriesWatchlist,
          [],
          {#tvSeriesTable: tvSeriesTable},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [id],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i19.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i19.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i19.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i19.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i20.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
      ) as _i7.Future<_i20.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
