// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIHe4SFTxflICbWI55v_0Frz-zustMfw',
    appId: '1:1053532551062:web:6b82d2524622b82ac24fb7',
    messagingSenderId: '1053532551062',
    projectId: 'dicoding-flutter-expert-5dae1',
    authDomain: 'dicoding-flutter-expert-5dae1.firebaseapp.com',
    storageBucket: 'dicoding-flutter-expert-5dae1.appspot.com',
    measurementId: 'G-CVHXMJ53V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPcViiMtP3KWQ35J4AcyvZ7h8act-u8Q',
    appId: '1:1053532551062:android:986670509c033c6bc24fb7',
    messagingSenderId: '1053532551062',
    projectId: 'dicoding-flutter-expert-5dae1',
    storageBucket: 'dicoding-flutter-expert-5dae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5p4IiNPzj84d7Zpqeg0YSo0OqwjWU2p4',
    appId: '1:1053532551062:ios:24eb3387a67e7800c24fb7',
    messagingSenderId: '1053532551062',
    projectId: 'dicoding-flutter-expert-5dae1',
    storageBucket: 'dicoding-flutter-expert-5dae1.appspot.com',
    iosClientId: '1053532551062-q60ddb07qs5nkjel0d8gbasvtmseppl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicodingFinalDitonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5p4IiNPzj84d7Zpqeg0YSo0OqwjWU2p4',
    appId: '1:1053532551062:ios:24eb3387a67e7800c24fb7',
    messagingSenderId: '1053532551062',
    projectId: 'dicoding-flutter-expert-5dae1',
    storageBucket: 'dicoding-flutter-expert-5dae1.appspot.com',
    iosClientId: '1053532551062-q60ddb07qs5nkjel0d8gbasvtmseppl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicodingFinalDitonton',
  );
}
